name: crypto_board
description: Flutter application

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
     - assets/icons/$pac.png
     - assets/icons/abt.png
     - assets/icons/act.png
     - assets/icons/ada.png
     - assets/icons/adx.png
     - assets/icons/ae.png
     - assets/icons/agi.png
     - assets/icons/agrs.png
     - assets/icons/aion.png
     - assets/icons/amb.png
     - assets/icons/amp.png
     - assets/icons/ant.png
     - assets/icons/apex.png
     - assets/icons/appc.png
     - assets/icons/ardr.png
     - assets/icons/ark.png
     - assets/icons/arn.png
     - assets/icons/ary.png
     - assets/icons/ast.png
     - assets/icons/atm.png
     - assets/icons/auto.png
     - assets/icons/bat.png
     - assets/icons/bay.png
     - assets/icons/bcc.png
     - assets/icons/bcd.png
     - assets/icons/bch.png
     - assets/icons/bcn.png
     - assets/icons/bco.png
     - assets/icons/bcpt.png
     - assets/icons/bdl.png
     - assets/icons/bela.png
     - assets/icons/bix.png
     - assets/icons/blcn.png
     - assets/icons/blk.png
     - assets/icons/block.png
     - assets/icons/blz.png
     - assets/icons/bnb.png
     - assets/icons/bnt.png
     - assets/icons/bnty.png
     - assets/icons/bos.png
     - assets/icons/bpt.png
     - assets/icons/bq.png
     - assets/icons/brd.png
     - assets/icons/btc.png
     - assets/icons/btcd.png
     - assets/icons/btcp.png
     - assets/icons/btcz.png
     - assets/icons/btg.png
     - assets/icons/btm.png
     - assets/icons/bts.png
     - assets/icons/btx.png
     - assets/icons/burst.png
     - assets/icons/cdn.png
     - assets/icons/cdt.png
     - assets/icons/cenz.png
     - assets/icons/chat.png
     - assets/icons/chips.png
     - assets/icons/cix.png
     - assets/icons/clam.png
     - assets/icons/cloak.png
     - assets/icons/cmt.png
     - assets/icons/cnd.png
     - assets/icons/cnx.png
     - assets/icons/cny.png
     - assets/icons/cob.png
     - assets/icons/cred.png
     - assets/icons/crpt.png
     - assets/icons/crw.png
     - assets/icons/cs.png
     - assets/icons/ctr.png
     - assets/icons/cvc.png
     - assets/icons/dash.png
     - assets/icons/dat.png
     - assets/icons/data.png
     - assets/icons/dbc.png
     - assets/icons/dcn.png
     - assets/icons/dcr.png
     - assets/icons/dent.png
     - assets/icons/dew.png
     - assets/icons/dgb.png
     - assets/icons/dgd.png
     - assets/icons/dlt.png
     - assets/icons/dnt.png
     - assets/icons/doge.png
     - assets/icons/drgn.png
     - assets/icons/dta.png
     - assets/icons/dtr.png
     - assets/icons/ebst.png
     - assets/icons/edg.png
     - assets/icons/edo.png
     - assets/icons/edoge.png
     - assets/icons/ela.png
     - assets/icons/elf.png
     - assets/icons/elix.png
     - assets/icons/ella.png
     - assets/icons/emc.png
     - assets/icons/emc2.png
     - assets/icons/eng.png
     - assets/icons/enj.png
     - assets/icons/eos.png
     - assets/icons/equa.png
     - assets/icons/etc.png
     - assets/icons/eth.png
     - assets/icons/ethos.png
     - assets/icons/etn.png
     - assets/icons/etp.png
     - assets/icons/eur.png
     - assets/icons/evx.png
     - assets/icons/exmo.png
     - assets/icons/exp.png
     - assets/icons/fair.png
     - assets/icons/fct.png
     - assets/icons/fil.png
     - assets/icons/fldc.png
     - assets/icons/flo.png
     - assets/icons/fsn.png
     - assets/icons/ftc.png
     - assets/icons/fuel.png
     - assets/icons/fun.png
     - assets/icons/game.png
     - assets/icons/gas.png
     - assets/icons/gbp.png
     - assets/icons/gbx.png
     - assets/icons/gbyte.png
     - assets/icons/generic.png
     - assets/icons/gno.png
     - assets/icons/gnt.png
     - assets/icons/grc.png
     - assets/icons/grs.png
     - assets/icons/gto.png
     - assets/icons/gup.png
     - assets/icons/gvt.png
     - assets/icons/gxs.png
     - assets/icons/hpb.png
     - assets/icons/hsr.png
     - assets/icons/html.png
     - assets/icons/huc.png
     - assets/icons/hush.png
     - assets/icons/icn.png
     - assets/icons/icx.png
     - assets/icons/ignis.png
     - assets/icons/ink.png
     - assets/icons/ins.png
     - assets/icons/ion.png
     - assets/icons/iop.png
     - assets/icons/iost.png
     - assets/icons/itc.png
     - assets/icons/jnt.png
     - assets/icons/jpy.png
     - assets/icons/kcs.png
     - assets/icons/kin.png
     - assets/icons/kmd.png
     - assets/icons/knc.png
     - assets/icons/krb.png
     - assets/icons/lbc.png
     - assets/icons/lend.png
     - assets/icons/link.png
     - assets/icons/lkk.png
     - assets/icons/lrc.png
     - assets/icons/lsk.png
     - assets/icons/ltc.png
     - assets/icons/lun.png
     - assets/icons/maid.png
     - assets/icons/mana.png
     - assets/icons/mcap.png
     - assets/icons/mco.png
     - assets/icons/mda.png
     - assets/icons/mds.png
     - assets/icons/med.png
     - assets/icons/miota.png
     - assets/icons/mith.png
     - assets/icons/mkr.png
     - assets/icons/mln.png
     - assets/icons/mnx.png
     - assets/icons/mod.png
     - assets/icons/mona.png
     - assets/icons/mth.png
     - assets/icons/mtl.png
     - assets/icons/music.png
     - assets/icons/mzc.png
     - assets/icons/nano.png
     - assets/icons/nas.png
     - assets/icons/nav.png
     - assets/icons/ncash.png
     - assets/icons/ndz.png
     - assets/icons/nebl.png
     - assets/icons/neo.png
     - assets/icons/neos.png
     - assets/icons/ngc.png
     - assets/icons/nlc2.png
     - assets/icons/nlg.png
     - assets/icons/nmc.png
     - assets/icons/nuls.png
     - assets/icons/nxs.png
     - assets/icons/nxt.png
     - assets/icons/oax.png
     - assets/icons/omg.png
     - assets/icons/omni.png
     - assets/icons/ont.png
     - assets/icons/ost.png
     - assets/icons/ox.png
     - assets/icons/part.png
     - assets/icons/pasl.png
     - assets/icons/pay.png
     - assets/icons/pink.png
     - assets/icons/pirl.png
     - assets/icons/pivx.png
     - assets/icons/plr.png
     - assets/icons/poa.png
     - assets/icons/poe.png
     - assets/icons/poly.png
     - assets/icons/pot.png
     - assets/icons/powr.png
     - assets/icons/ppc.png
     - assets/icons/ppp.png
     - assets/icons/ppt.png
     - assets/icons/prl.png
     - assets/icons/pura.png
     - assets/icons/qash.png
     - assets/icons/qiwi.png
     - assets/icons/qlc.png
     - assets/icons/qrl.png
     - assets/icons/qsp.png
     - assets/icons/qtum.png
     - assets/icons/r.png
     - assets/icons/rads.png
     - assets/icons/rcn.png
     - assets/icons/rdd.png
     - assets/icons/rdn.png
     - assets/icons/rep.png
     - assets/icons/req.png
     - assets/icons/rhoc.png
     - assets/icons/ric.png
     - assets/icons/rise.png
     - assets/icons/rlc.png
     - assets/icons/rpx.png
     - assets/icons/rub.png
     - assets/icons/rvn.png
     - assets/icons/salt.png
     - assets/icons/san.png
     - assets/icons/sbd.png
     - assets/icons/sberbank.png
     - assets/icons/sc.png
     - assets/icons/sky.png
     - assets/icons/slr.png
     - assets/icons/sls.png
     - assets/icons/smart.png
     - assets/icons/sngls.png
     - assets/icons/snm.png
     - assets/icons/snt.png
     - assets/icons/spank.png
     - assets/icons/sphtx.png
     - assets/icons/srn.png
     - assets/icons/start.png
     - assets/icons/steem.png
     - assets/icons/storj.png
     - assets/icons/storm.png
     - assets/icons/strat.png
     - assets/icons/sub.png
     - assets/icons/sys.png
     - assets/icons/taas.png
     - assets/icons/tau.png
     - assets/icons/tel.png
     - assets/icons/theta.png
     - assets/icons/tix.png
     - assets/icons/tkn.png
     - assets/icons/tnb.png
     - assets/icons/tnc.png
     - assets/icons/tnt.png
     - assets/icons/trig.png
     - assets/icons/trx.png
     - assets/icons/tzc.png
     - assets/icons/ubq.png
     - assets/icons/unity.png
     - assets/icons/usd.png
     - assets/icons/usdt.png
     - assets/icons/utk.png
     - assets/icons/ven.png
     - assets/icons/veri.png
     - assets/icons/via.png
     - assets/icons/vib.png
     - assets/icons/vibe.png
     - assets/icons/vivo.png
     - assets/icons/vrc.png
     - assets/icons/vtc.png
     - assets/icons/wabi.png
     - assets/icons/wan.png
     - assets/icons/waves.png
     - assets/icons/wax.png
     - assets/icons/wgr.png
     - assets/icons/wings.png
     - assets/icons/wpr.png
     - assets/icons/wtc.png
     - assets/icons/xas.png
     - assets/icons/xbc.png
     - assets/icons/xby.png
     - assets/icons/xcp.png
     - assets/icons/xdn.png
     - assets/icons/xem.png
     - assets/icons/xlm.png
     - assets/icons/xmg.png
     - assets/icons/xmr.png
     - assets/icons/xmy.png
     - assets/icons/xp.png
     - assets/icons/xpa.png
     - assets/icons/xpm.png
     - assets/icons/xrp.png
     - assets/icons/xtz.png
     - assets/icons/xuc.png
     - assets/icons/xvc.png
     - assets/icons/xvg.png
     - assets/icons/xzc.png
     - assets/icons/yoyow.png
     - assets/icons/zcl.png
     - assets/icons/zec.png
     - assets/icons/zen.png
     - assets/icons/zil.png
     - assets/icons/zrx.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
